//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcAthleticsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int AnnouncementID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTime { get; set; }
        public int EventID { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
