//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcAthleticsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int ExerciseID { get; set; }
        public int WorkoutID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sets { get; set; }
        public Nullable<int> Reps { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<bool> Completed { get; set; }
    
        public virtual Workout Workout { get; set; }
    }
}
