//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcAthleticsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workout()
        {
            this.Exercises = new HashSet<Exercise>();
        }
    
        public int WorkoutID { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> EventID { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exercise> Exercises { get; set; }
        public virtual User User { get; set; }
    }
}
