#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GCAthletics.Droid.Resource", IsApplication=true)]

namespace GCAthletics.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int alertsButton = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int calendarButton = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int emailField = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int loginButton = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int mainScreenGridLayout = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int passwordField = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int teamButton = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int textAthleteName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int textPosition = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int textTeam = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int textWelcome = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int thunderImage = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int workoutsButton = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HomeScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int ccc = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dumbell = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int megaphone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int people = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int thunder = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int user = 2130837510;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int athleteName = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int position = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int team = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
